server:
  port: 7770
spring:
  application:
    name: product-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/aigou-product?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

